server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: ${badminton.datasource.driver-class-name}
    url: jdbc:mysql://${badminton.datasource.host}:${badminton.datasource.port}/${badminton.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${badminton.datasource.username}
    password: ${badminton.datasource.password}
  data:
    redis:
      host: 127.0.0.1  # 地址
      port: 6379  # 端口号
      database: 0  # 数据库索引（默认为0）
      timeout: 1800000  # 连接超时时间（毫秒）
      lettuce:
        pool:
          max-active: 20  # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1  # 最大阻塞等待时间（负数表示没有限制）
          max-idle: 5  # 连接池中最大空闲连接
          min-idle: 0  # 连接池中最小空闲连接

mybatis:
  # mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.badmintonsport.pojo.entity
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

BadmintonSport:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: BadmintonSportwoyebuzhidaoweishenmeyaozhemechang
    # 设置jwt过期时间
    admin-ttl: 720000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token


#  alioss:
#    endpoint: ${sky.alioss.endpoint}
#    access-key-id: ${sky.alioss.access-key-id}
#    access-key-secret: ${sky.alioss.access-key-secret}
#    bucket-name: ${sky.alioss.bucket-name}
